### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wjczf123** [xmshi-trio/MSL#2]
I use `python train.py conf/train.json` to run your code and find that FileNotFoundError: [Errno 2] No such file or directory: 'conf/train.json'.
I also try `python train.py conf/train_rcnn.json`. It doesn't work.
What are the training instruction?

**Comment by xmshi-trio** [comment]
Have you try `python train.py ./conf/train_cnn.json`?

**Comment by wjczf123** [comment]
I run `python train.py conf/train_rcnn.json` and `python train.py conf/train_cnn.json`.
The result is: 
OSError: Can't load config for '/dockerdata/xiaomingshi/chinese_L-12_H-768_A-12'. Make sure that:
- '/dockerdata/xiaomingshi/chinese_L-12_H-768_A-12' is a correct model identifier listed on 'https://huggingface.co/models'
- or '/dockerdata/xiaomingshi/chinese_L-12_H-768_A-12' is the correct path to a directory containing a config.json file.

Then I modify "pretrained_bert_embedding": "bert-base-chinese" in train_cnn.json Line 44.
Then the result is; JSONDecodeError: Expecting property name enclosed in double quotes: line 44 column 5 (char 1145).
