### ISSUE TITLE
What are the versions of torch and transformers

### ISSUE THREAD

**Issue by FlyingCat-fa** [xmshi-trio/MSL#5]
When I run train.py with train_cnn.json:
There is a error "dataset attribute should not be set after DataLoader is initialized" in trans_id_to_bert_embedding:
data_loader.dataset = output_dataset

Could tell me the versions of torch and transformers ? Thanks.

**Comment by xmshi-trio** [comment]
The version of torch is 1.0.0, and the version of transformers is 2.7.0
